/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import color2048 from "./script/color2048"
import New2048 from "./script/New2048"
import Mine from "./script/Mine"
import GameUI from "./script/GameUI"
import GameControl from "./script/GameControl"
import boomset from "./script/boomset"
import Bullet from "./script/Bullet"
import DropBox from "./script/DropBox"
import noboomset from "./script/noboomset"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=640;
    static height:number=1136;
    static scaleMode:string="fixedwidth";
    static screenMode:string="none";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="20481.scene";
    static sceneRoot:string="";
    static debug:boolean=true;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("script/color2048.ts",color2048);
        reg("script/New2048.ts",New2048);
        reg("script/Mine.ts",Mine);
        reg("script/GameUI.ts",GameUI);
        reg("script/GameControl.ts",GameControl);
        reg("script/boomset.ts",boomset);
        reg("script/Bullet.ts",Bullet);
        reg("script/DropBox.ts",DropBox);
        reg("script/noboomset.ts",noboomset);
    }
}
GameConfig.init();